// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WellmanReactCore.Server.Models;

#nullable disable

namespace WellmanReactCore.Server.Migrations
{
    [DbContext(typeof(WellmanContext))]
    partial class WellmanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WellmanReactCore.Server.Models.Well", b =>
                {
                    b.Property<int>("WellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WellId"));

                    b.Property<int>("CutOrFill")
                        .HasColumnType("int");

                    b.Property<string>("GeographicArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ground")
                        .HasColumnType("int");

                    b.Property<int>("KBToGround")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WellLicenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("WellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WellId");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("WellmanReactCore.Server.Models.WellBore", b =>
                {
                    b.Property<int>("WellBoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WellBoreId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WellId")
                        .HasColumnType("int");

                    b.Property<string>("WellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WellBoreId");

                    b.HasIndex("WellId");

                    b.ToTable("WellBores");
                });

            modelBuilder.Entity("WellmanReactCore.Server.Models.WellBore", b =>
                {
                    b.HasOne("WellmanReactCore.Server.Models.Well", "Well")
                        .WithMany("WellBores")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("WellmanReactCore.Server.Models.Well", b =>
                {
                    b.Navigation("WellBores");
                });
#pragma warning restore 612, 618
        }
    }
}
